2020-09-29 19:03:44,072 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:03:44,085 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:03:44,085 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:04:54,578 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:04:54,592 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:04:54,592 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:07:29,936 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:07:29,949 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:07:29,949 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:19:12,234 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:19:12,316 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:19:12,316 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:42:22,722 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:42:22,732 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:42:22,732 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:44:01,891 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:44:01,906 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:44:01,906 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:44:38,577 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:44:38,587 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:44:38,587 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:45:22,380 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:45:22,403 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 19:45:22,403 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 20:23:57,308 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 20:23:57,332 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 20:23:57,332 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 20:27:51,088 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 20:27:51,123 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-09-29 20:27:51,123 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:14:55,523 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:14:55,542 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:14:55,542 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:15:43,422 ERROR: Exception on /age/target.png [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/flaskgur/flaskgur.py", line 150, in age
    detect_age(os.path.join(current_app.config['UPLOAD_DIR'], secure_filename(filename)))
  File "/home/mmaitland300/flask/webproject/app/flaskgur/alt.py", line 51, in detect_age
    faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-yln3mf6z/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "deploy.prototxt" in function 'ReadProtoFromTextFile'

2020-10-02 20:15:43,422 ERROR: Exception on /age/target.png [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/flaskgur/flaskgur.py", line 150, in age
    detect_age(os.path.join(current_app.config['UPLOAD_DIR'], secure_filename(filename)))
  File "/home/mmaitland300/flask/webproject/app/flaskgur/alt.py", line 51, in detect_age
    faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-yln3mf6z/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "deploy.prototxt" in function 'ReadProtoFromTextFile'

2020-10-02 20:31:55,345 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:31:55,374 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:31:55,374 INFO: Matts brain startup [in /home/mmaitland300/flask/webproject/app/__init__.py:95]
2020-10-02 20:32:05,999 ERROR: Exception on /age/target.png [GET] [in /home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mmaitland300/.virtualenvs/webproject/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mmaitland300/flask/webproject/app/flaskgur/flaskgur.py", line 150, in age
    detect_age(os.path.join(current_app.config['UPLOAD_DIR'], secure_filename(filename)))
  File "/home/mmaitland300/flask/webproject/app/flaskgur/alt.py", line 51, in detect_age
    faceNet = cv2.dnn.readNet(prototxtPath, weightsPath)
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-yln3mf6z/opencv/modules/dnn/src/caffe/caffe_io.cpp:1121: error: (-2:Unspecified error) FAILED: fs.is_open(). Can't open "/home/mmaitland300/flask/webproject/deploy.prototxt" in function 'ReadProtoFromTextFile'

